### ISSUE TITLE
LWC vs Visualforce+Reactjs

### ISSUE THREAD

**Issue by mpadmaraj** [pozil/salesforce-react-integration#4]
I was going thru the video where you explained the approach. it is a great tutorial! We are evaluating Visualforce with Reactjs vs LWC in one of our new implementations. Are there any cons of going with the approach of using Visuaforce wih Reactjs?

**Comment by pozil** [comment]
Thanks for the feedback.

To clarify things, this project demonstrate how you can create a standalone React app that connects to the Salesforce Platform. It's not related to Visualforce.

To answer your question, I advise against building anything new on the Platform with Visualforce because this is legacy technology. For on-platform apps, you should invest in LWC which is clearly the future because it embraces web standards.

Note that React is still great for off-platform apps because there are a lot of community contributions that you can use. The only downside of React is that it's not embracing web standards so it may not be future proof.

**Comment by saloni509** [comment]
This is a very nice one and gives in-depth information. I am really happy with the quality and presentation of the article. I’d really like to appreciate the efforts you get with writing this post. Thanks for sharing.
[salesforce classes in pune](https://www.sevenmentor.com/salesforce-training-in-pune.php
)
[salesforce course in pune](https://www.sevenmentor.com/salesforce-training-in-pune.php
)
